sudo: required

language: go
go:
    - tip

services:
      - docker

before_install:
    - go get github.com/axw/gocov/gocov
    - go get github.com/mattn/goveralls
    - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
    - $HOME/gopath/bin/goveralls -repotoken $COVERALLS_TOKEN ./...
after_success:
    - docker login -e=$DOCKER_EMAIL -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
    - docker build -t tommynov/devopsforgolang .
    - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && docker push tommynov/devopsforgolang
